name: CI/CD IMC App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar Lint
        run: npx eslint src/

      - name: Rodar Testes
        run: npm test

      - name: Build (simulado)
        run: echo "Build feito!"

      - name: Deploy Staging (simulado)
        run: echo "Deploy para staging feito!"

      - name: Deploy Produção (simulado)
        if: github.ref == 'refs/heads/main'
        run: echo "Deploy em produção feito!"
